project:
  type: website

website:
  description: "A blog about my musings on various topics."
  site-url: my-musings.mukundrb.com # you must change this appropriately for RSS feeds to work properly
  title: "My Musings"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mukund-mpp
format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css



